In [6]:
import html5lib 
import pandas as pd
mp2017 = pd.read_html("https://en.wikipedia.org/wiki/List_of_MPs_elected_in_the_United_Kingdom_general_election,_2017")

In [7]:
def extract_name(duplicate_name):
    """Extracts names from the wikipedia column, as the first name is there twice"""
    first_name = ""
    last_c = " "
    for c in duplicate_name:
        if (last_c != " " and c.isupper()):#If the name repeats, we found the first name
            return first_name
        else:#We haven't found the first name, continue and add the character to it
            first_name += c
            last_c = c
            

mps = pd.DataFrame()
last_name = []
first_name = []
party = []
for mp in mp2017[3][4][1:]:
    one_party = mp.split('(')
    party_symbol = one_party[1].split(')')[0]
    party.append(party_symbol)
    one_name = mp.split(",")
    last_name.append(one_name[0])
    if ('Jr.' in one_name[1]):
        first_name.append(extract_name(one_name[2]))
    else:
        first_name.append(extract_name(one_name[1]))
mps['first_name'] = first_name
mps['last_name'] = last_name
mps['party'] = party

In [8]:
mps

             first_name  last_name    party
0      The Hon. Stephen    Kinnock        L
1                  Guto       Bebb        C
2                Kirsty   Blackman      SNP
3                  Ross    Thomson        C
4                  Neil       Gray      SNP
5                   Leo   Docherty        C
6                 Wendy     Morton        C
7                Graham      Brady        C
8                  Mark       Tami        L
9                 Nigel      Mills        C
10             Kirstene       Hair        C
11                Hywel   Williams       PC
12              Brendan     O'Hara      SNP
13                 Nick    Herbert        C
14               Gloria   De Piero        L
15               Damian      Green        C
16               Angela     Rayner        L
17                David  Lidington        C
18                 Bill      Grant        C
19    The Hon. Victoria    Prentis        C
20                David     Duguid        C
21        Dame Margaret      Hodge        L
22                  Dan     Jarvis        L
23            Stephanie    Peacock        L
24                 John   Woodcock  L Co-op
25                 John      Baron        C
26                Maria     Miller        C
27                 John       Mann        L
28                 Wera   Hobhouse       LD
29                Tracy     Brabin  L Co-op
..                  ...        ...      ...
620               Karen       Buck        L
621                 Tim     Farron       LD
622                John    Penrose        C
623                Lisa      Nandy        L
624             Stephen    Hammond        C
625               Steve      Brine        C
626                Adam    Afriyie        C
627              Alison   McGovern        L
628            Margaret  Greenwood        L
629               Priti      Patel        C
630              Robert     Courts        C
631            Jonathan       Lord        C
632                John    Redwood        C
633                Emma   Reynolds        L
634                 Pat   McFadden        L
635             Eleanor      Smith        L
636      The Hon. Robin     Walker        C
637                 Sue     Hayman        L
638             Barbara     Keeley        L
639           Sir Peter  Bottomley        C
640                Mark  Pritchard        C
641                 Ian      Lucas        L
642               Steve      Baker        C
643                 Ben    Wallace        C
644                Mark    Garnier        C
645                Mike       Kane        L
646              Marcus       Fysh        C
647              Albert       Owen        L
648             Rachael    Maskell  L Co-op
649              Julian     Sturdy        C

[650 rows x 3 columns]